### ISSUE TITLE
Add Nullable and NotNullable type aliases

### ISSUE THREAD

**Issue by ocharles** [circuithub/rel8#23]
Writing `IsMaybe a ~ 'False` is an indirect way of saying `NotNullable a`. The latter is clearer (there's more intent), and also saves users incurring a `DataKinds` extension.

My suggestion is:

```haskell
type NotNullable a = (DBType a, IsMaybe a ~ 'False)
type Nullable a = (DBType a, IsMaybe a ~ 'True)
```

though maybe pushing that `DBType` in is a bit too much.

**Comment by ocharles** [comment]
Alternatively maybe we do this with a proper class so we can add better error messages.

**Comment by shane-circuithub** [comment]
I would leave `DBType` out, because that's a separate concern, and it's also wrong in the `Nullable` case (there is no `a` that can satisfy both `DBType a` and `IsMaybe a ~ 'True`). But I agree something like this would be nice to have.

I've also been tempted a few times to put `IsMaybe a ~ 'False` as a superclass of `DBType` itself, so at least if you already have `DBType a` you don't have to also say `IsMaybe a ~ 'False`, which ought to be the case anyway.

**Comment by ocharles** [comment]
> I've also been tempted a few times to put IsMaybe a ~ 'False as a superclass of DBType

Ok, cool - I've also thought about doing this. It sounds like we should probably do this (or `NotNullable a => DBType a`)

**Comment by shane-circuithub** [comment]
I added a `NotNull` constraint synonym for this. I didn't like the look of `NotNullable`, it looks too much like `NonNullable`, and at `NotNull` makes you think of SQL's `NOT NULL`. I didn't add a corresponding `Nullable`, because `IsMaybe a ~ 'True` is kind of useless, it just means you're talking about a `Maybe a`, in which case you'd just say that directly. Every single usage of `IsMaybe` we had was testing `~ False` anyway so I think that's all we need.
