### ISSUE TITLE
How to insert and return an auto-generated value

### ISSUE THREAD

**Issue by chris-martin** [circuithub/rel8#74]
I have a typical sort of situation here where there's a table with an auto-incrementing ID (the "position" column in the schema below)...

```haskell
data StripeCustomerQueue f = StripeCustomerQueue
  { stripeCustomerQueuePosition :: Column f StripeCustomerQueuePosition
  , stripeCustomerQueueCustomerId :: Column f StripeCustomerId
  , stripeCustomerQueueLiveMode :: Column f LiveMode
  }
  deriving stock (Generic)
  deriving anyclass (Rel8able)
```

... and I want to [insert](https://www.postgresql.org/docs/12/sql-insert.html) into the table, let the database set the position field to its default value, and return the generated value.

```haskell
Insert
  { into = stripeCustomerQueueSchema
  , rows = one $ StripeCustomerQueue
      { stripeCustomerQueueLiveMode = lit mode
      , stripeCustomerQueueCustomerId = lit customerId
      , stripeCustomerQueuePosition = _
      }
  , onConflict = Abort
  , returning = Projection stripeCustomerQueuePosition
  }
```

What do I put in the hole above? Should I write `unsafeLiteral "DEFAULT"`? Or is there some other approach I'm missing?

**Comment by ocharles** [comment]
A great question! We certainly need to document this, but here are a few solutions at the moment:

1. Use `unsafeLiteral "DEFAULT"`, as you mentioned. We haven't exported this as a definition (e.g., `defaultValue = unsafeLiteral "DEFAULT"`) due to its, well, unsafeness.
2. Don't rely on the default at all, and instead write an actual expression. In this case I don't know what the default of `position` would be, but in the typical case of wanting an auto-incremented id, you can use https://hackage.haskell.org/package/rel8-1.0.0.1/docs/Rel8.html#v:nextval.

Rel8 actually used to have special support for default values, with a special insertion context - but that was removed in https://github.com/circuithub/rel8/commit/1eaa683513729fb0517b8ba12899a7c1ad811a25. Ultimately we felt that tracking all of this at the type level was just too much. It also put the definition in the `Rel8able`, but a `Rel8able` can be used with many different tables, not all of which may share the same defaulting, so that was also slightly dubious.

I hope this helps. I'll keep this open as a reminder to add documentation about `INSERT`, `UPDATE` and `DELETE`.

**Comment by chris-martin** [comment]
It sure would be nice if the `TableSchema` could specify which columns were defaultable, but it doesn't seem particularly dissatisfying to me to use `unsafeLiteral "DEFAULT"` and accept the runtime error if I attempt to default something that is not defaultable.
