### ISSUE TITLE
Use minExpr and maxExpr instead of leastExpr and greatestExpr?

### ISSUE THREAD

**Issue by tomjaguarpaw** [circuithub/rel8#78]
Rel8 has [`leastExpr` and `greatestExpr`](https://hackage.haskell.org/package/rel8-1.0.0.0/docs/Rel8.html#v:leastExpr) that correspond to Haskell `min` and `max`. Since Rel8 adopts Haskell naming over Postgres naming wouldn't `minExpr` and `maxExpr` be better names?

**Comment by shane-circuithub** [comment]
We also have `least` and `greatest` which are "tabular" versions of the above functions, so they would have to be renamed too. I didn't want to name them `min` and `max` because that would clash with the `Prelude`. Obviously I'm not opposed to clashing with the Prelude names, but the fact that Postgres had its own names for these functions gave me a convenient way out of having to make that choice. If you still think `min` and `max` would be better though then I'm open to considering that.

**Comment by tomjaguarpaw** [comment]
I don't feel very strongly. Opaleye is half-hearted about whether it uses Haskell names or Postgres names. I got the sense that Rel8 was going all the way with Haskell names and not letting anything Postgres-related leak through. But if you prefer to use Postgres-related naming sometimes that's fine by me too.
