### ISSUE TITLE
How to run multiple queries in a transaction

### ISSUE THREAD

**Issue by chris-martin** [circuithub/rel8#82]
- With postgresql-simple, I would wrap the IO in [withTransaction](https://hackage.haskell.org/package/postgresql-simple-0.6.4/docs/Database-PostgreSQL-Simple-Transaction.html) or one of its related functions.
- If I were writing hasql `Statement`s, I would use [hasql-transaction](https://hackage.haskell.org/package/hasql-transaction-1.0.0.2/docs/Hasql-Transaction.html).

Is there likewise an answer for this with rel8? Do I need to drop down to the level of the `hasql` package and write [Statement](https://hackage.haskell.org/package/hasql-1.4.5.1/docs/Hasql-Statement.html)s for "begin transaction", "commit", etc?

**Comment by ocharles** [comment]
> Do I need to drop down to the level of the hasql package and write Statements for "begin transaction", "commit", etc?

Currently, yes. Rel8 intentionally currently only exports `Connection -> IO ()` type functions to be as un-opinionated as possible. However, many people have suggested this is a pretty painful, and in practice we have wrapped this internally at CircuitHub with our own effect system to deal with this. It's unclear to me what the right API is, though. If you have any thoughts, I'm all ears!

**Comment by shane-circuithub** [comment]
I don't see any real downside to exporting the `select`, `insert`, etc. functions in Hasql's `Statement` monad rather than `Connection -> IO ()`. People will have to depend on and import `hasql` to construct a `Connection` anyway, so they can easily use `run` to recover a `Connection -> IO a` function if that's what they'd rather work with. But it's much more convenient to use things like `hasql-pool` and `hasql-transaction`. I don't think this is even "opinionated", because it doesn't preclude somebody using a different solution — like I said, they can easily recover the current API with `run` if they wanted to use something different.

**Comment by ocharles** [comment]
Yea, I was also thinking of doing that - we already require people depend on `hasql` anyway to `acquire` a `Connection`.

**Comment by chris-martin** [comment]
It does seem like rel8 is currently straddling an awkward middle ground between being a full-fledged complete way to interact with your database, and being merely one part of the hasql ecosystem. I wonder if perhaps it would benefit from a clear decision one way or the other?
